"""empty message

Revision ID: 27cf771854ad
Revises: 356b8a2e1879
Create Date: 2024-04-13 17:59:22.685073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cf771854ad'
down_revision = '356b8a2e1879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('duracion', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('destino', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('duracion', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('duracion', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_final', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_tour', sa.Integer(), nullable=True),
    sa.Column('id_paquetes', sa.Integer(), nullable=True),
    sa.Column('id_hotel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_hotel'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['id_paquetes'], ['paquetes.id'], ),
    sa.ForeignKeyConstraint(['id_tour'], ['tours.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('tours')
    op.drop_table('paquetes')
    op.drop_table('hotel')
    # ### end Alembic commands ###
