"""empty message

Revision ID: 2ce2c2b70625
Revises: 42d14468c2ec
Create Date: 2024-04-14 18:57:25.112576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ce2c2b70625'
down_revision = '42d14468c2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_final', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_tour', sa.Integer(), nullable=True),
    sa.Column('id_paquete', sa.Integer(), nullable=True),
    sa.Column('id_hotel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_hotel'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['id_paquete'], ['paquete.id'], ),
    sa.ForeignKeyConstraint(['id_tour'], ['tour.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reservas')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.create_table('reservas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_final', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_tour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_paquete', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_hotel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_hotel'], ['hotel.id'], name='reservas_id_hotel_fkey'),
    sa.ForeignKeyConstraint(['id_paquete'], ['paquete.id'], name='reservas_id_paquete_fkey'),
    sa.ForeignKeyConstraint(['id_tour'], ['tour.id'], name='reservas_id_tour_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='reservas_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='reservas_pkey')
    )
    op.drop_table('reserva')
    # ### end Alembic commands ###
