"""empty message

Revision ID: 47edae46f14f
Revises: f7346f3d8488
Create Date: 2024-04-13 23:03:18.176025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47edae46f14f'
down_revision = 'f7346f3d8488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('destino', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('duracion', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paquetes')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_package', sa.Integer(), nullable=True))
        batch_op.drop_constraint('reservas_id_paquetes_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'package', ['id_package'], ['id'])
        batch_op.drop_column('id_paquetes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_paquetes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservas_id_paquetes_fkey', 'paquetes', ['id_paquetes'], ['id'])
        batch_op.drop_column('id_package')

    op.create_table('paquetes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('destino', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('duracion', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('precio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='paquetes_pkey')
    )
    op.drop_table('package')
    # ### end Alembic commands ###
