"""empty message

Revision ID: 541f669b708c
Revises: 922025187446
Create Date: 2024-05-03 15:29:26.875895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541f669b708c'
down_revision = '922025187446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageURL', sa.String(length=500), nullable=False))

    with op.batch_alter_table('paquete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageURL', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquete', schema=None) as batch_op:
        batch_op.drop_column('imageURL')

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('imageURL')

    # ### end Alembic commands ###
