"""empty message

Revision ID: 9eacd4b1ead2
Revises: 2ce2c2b70625
Create Date: 2024-05-02 20:33:46.792449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eacd4b1ead2'
down_revision = '2ce2c2b70625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageURL', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('imageURL')

    # ### end Alembic commands ###
