"""empty message

Revision ID: bfcc39256ed2
Revises: 27cf771854ad
Create Date: 2024-04-13 21:53:07.992464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfcc39256ed2'
down_revision = '27cf771854ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('duracion', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tours')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_constraint('reservas_id_tour_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tour', ['id_tour'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservas_id_tour_fkey', 'tours', ['id_tour'], ['id'])

    op.create_table('tours',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('duracion', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('precio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tours_pkey')
    )
    op.drop_table('tour')
    # ### end Alembic commands ###
